[package]
name = "c3_pilot_vault"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "c3_pilot_vault"

[features]
default = []
no-entrypoint = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
local-mock = []
local-jupiter-probe = []
local-jupiter-cycle = []

[dependencies]
anchor-lang = "=0.31.1"
anchor-spl = { version = "=0.31.1", features = ["token", "token_2022", "associated_token"] }
