/** Isolated owner-pilot copy; not imported by the stable Expo Router tree. */
export const pilotCopy = {
  en: {
    title: 'C3 owner pilot',
    dashboard: 'Dashboard',
    buy: 'Buy C3',
    sell: 'Sell C3',
    status: 'Intent status',
    activity: 'Activity',
    blocked: 'Mainnet pilot disabled',
    blockedDetail:
      'The C3 vault, share mint and security approvals are not yet available. No wallet action is possible.',
    navUnavailable: 'NAV temporarily unavailable',
    shareBalance: 'C3 share balance unavailable',
    usdcBalance: 'USDC balance unavailable',
    position: 'Verified C3 position unavailable',
    target: 'Target: 40% Bitcoin · 30% Ethereum · 30% Solana',
    pilotRisk: 'Experimental owner-only pilot. Real funds are at risk if a later approved test is performed.',
    fixedAmount: 'Acceptance-test amount: exactly 1 USDC, not a commercial minimum.',
    networkCosts: 'Protocol and network costs unavailable',
    fee: 'C Market fee: 0 for the protocol acceptance test',
    twoApprovals: 'Deposit requires two separate wallet approvals. The steps are not atomic.',
    sellDisclosure:
      'Experimental keep_tokens: [] redemption; USDC output and minimum are not guaranteed by the public SDK.',
    sellStages: 'Redemption, vault rebalance and USDC claim are separate stages. Never retry automatically.',
    shareAmount: 'Share amount unavailable',
    approve: 'Wallet approval unavailable',
    statusUnknown: 'No verified intent status',
    noActivity: 'No finalized C3 activity',
    manualReview: 'Uncertain results require manual review. A signature alone is not success.',
    explorer: 'Explorer links appear only for verified signatures.',
  },
  es: {
    title: 'Piloto C3 del propietario',
    dashboard: 'Panel',
    buy: 'Comprar C3',
    sell: 'Vender C3',
    status: 'Estado de la orden',
    activity: 'Actividad',
    blocked: 'Piloto Mainnet desactivado',
    blockedDetail:
      'Faltan la bóveda C3, el token de participación y las aprobaciones de seguridad. No es posible operar con la wallet.',
    navUnavailable: 'NAV temporalmente no disponible',
    shareBalance: 'Saldo C3 no disponible',
    usdcBalance: 'Saldo USDC no disponible',
    position: 'Posición C3 verificada no disponible',
    target: 'Objetivo: 40% Bitcoin · 30% Ethereum · 30% Solana',
    pilotRisk:
      'Piloto experimental solo para el propietario. Una prueba futura aprobada pondría fondos reales en riesgo.',
    fixedAmount: 'Importe de aceptación: exactamente 1 USDC; no es un mínimo comercial.',
    networkCosts: 'Costos del protocolo y la red no disponibles',
    fee: 'Comisión C Market: 0 para la prueba de aceptación',
    twoApprovals: 'El depósito requiere dos aprobaciones separadas. Los pasos no son atómicos.',
    sellDisclosure: 'Redención experimental keep_tokens: []; el SDK público no garantiza USDC ni un mínimo de salida.',
    sellStages: 'Redención, rebalanceo y cobro de USDC son etapas separadas. Sin reintento automático.',
    shareAmount: 'Cantidad de participaciones no disponible',
    approve: 'Aprobación de wallet no disponible',
    statusUnknown: 'No hay estado verificado',
    noActivity: 'No hay actividad C3 finalizada',
    manualReview: 'Un resultado incierto requiere revisión manual. Una firma no demuestra éxito.',
    explorer: 'Los enlaces de Explorer solo aparecen para firmas verificadas.',
  },
  'zh-CN': {
    title: 'C3 所有者试点',
    dashboard: '概览',
    buy: '购买 C3',
    sell: '卖出 C3',
    status: '意向状态',
    activity: '活动记录',
    blocked: '主网试点已禁用',
    blockedDetail: 'C3 金库、份额代币和安全批准尚未就绪。目前不能进行钱包操作。',
    navUnavailable: 'NAV 暂不可用',
    shareBalance: 'C3 份额余额不可用',
    usdcBalance: 'USDC 余额不可用',
    position: '已验证的 C3 持仓不可用',
    target: '目标：40% 比特币 · 30% 以太坊 · 30% Solana',
    pilotRisk: '仅供所有者的实验试点。未来获批测试仍有真实资金风险。',
    fixedAmount: '验收测试金额：恰好 1 USDC，并非商业最低购买额。',
    networkCosts: '协议和网络费用不可用',
    fee: '协议验收测试期间 C Market 手续费为 0',
    twoApprovals: '存款需要两次单独的钱包批准，步骤不是原子性的。',
    sellDisclosure: '实验性 keep_tokens: [] 赎回；公开 SDK 不保证 USDC 输出或最低到账额。',
    sellStages: '赎回、金库再平衡和 USDC 领取是不同阶段，不会自动重试。',
    shareAmount: '份额数量不可用',
    approve: '钱包批准不可用',
    statusUnknown: '没有已验证的意向状态',
    noActivity: '没有已完成的 C3 活动',
    manualReview: '不确定结果需要人工审核。仅有交易签名不代表成功。',
    explorer: '仅对已验证签名显示 Explorer 链接。',
  },
  'pt-BR': {
    title: 'Piloto C3 do proprietário',
    dashboard: 'Painel',
    buy: 'Comprar C3',
    sell: 'Vender C3',
    status: 'Status da intenção',
    activity: 'Atividade',
    blocked: 'Piloto Mainnet desativado',
    blockedDetail:
      'O cofre C3, o token de cotas e as aprovações de segurança ainda não estão disponíveis. Nenhuma ação da carteira é possível.',
    navUnavailable: 'NAV temporariamente indisponível',
    shareBalance: 'Saldo de cotas C3 indisponível',
    usdcBalance: 'Saldo USDC indisponível',
    position: 'Posição C3 verificada indisponível',
    target: 'Meta: 40% Bitcoin · 30% Ethereum · 30% Solana',
    pilotRisk: 'Piloto experimental só para o proprietário. Um teste futuro aprovado envolve risco de fundos reais.',
    fixedAmount: 'Valor de aceitação: exatamente 1 USDC, não um mínimo comercial.',
    networkCosts: 'Custos de protocolo e rede indisponíveis',
    fee: 'Taxa C Market: 0 no teste de aceitação',
    twoApprovals: 'O depósito exige duas aprovações separadas da carteira. As etapas não são atômicas.',
    sellDisclosure:
      'Resgate experimental keep_tokens: []; o SDK público não garante saída em USDC nem mínimo recebido.',
    sellStages: 'Resgate, rebalanceamento e recebimento de USDC são etapas separadas. Sem nova tentativa automática.',
    shareAmount: 'Quantidade de cotas indisponível',
    approve: 'Aprovação da carteira indisponível',
    statusUnknown: 'Nenhum status verificado',
    noActivity: 'Nenhuma atividade C3 finalizada',
    manualReview: 'Resultado incerto exige revisão manual. Uma assinatura não comprova sucesso.',
    explorer: 'Links do Explorer aparecem apenas para assinaturas verificadas.',
  },
} as const

export type PilotLocale = keyof typeof pilotCopy
export type PilotCopyKey = keyof typeof pilotCopy.en

export function getPilotCopy(locale: PilotLocale, key: PilotCopyKey): string {
  return pilotCopy[locale][key] ?? pilotCopy.en[key]
}
