import { C3_MAINNET_EXECUTION_CAPABILITY } from "../../src/constants.ts";
import { INTEGRATION_BLOCKER } from "./integration-contract.ts";

const rows = {
  SDK_API_DISCOVERED: "PARTIAL_PUBLIC_ARTIFACT",
  DEPOSIT_BUILD_VERIFIED: "PUBLIC_EXAMPLE_UNSIGNED_ONLY",
  SHARE_EFFECTS_VERIFIED: "PUBLIC_SAMPLE_ONLY",
  USDC_REDEMPTION_BUILD_VERIFIED: "BLOCKED_NO_EXPLICIT_OUTPUT_MINT",
  PUBLIC_TRANSACTION_CORRELATION: "CONSISTENT_BUT_UNVERIFIED",
  PRODUCTION_POLICY_APPROVED: false,
  MAINNET_EXECUTION_ENABLED: C3_MAINNET_EXECUTION_CAPABILITY,
} as const;
if (C3_MAINNET_EXECUTION_CAPABILITY !== false)
  throw new Error(INTEGRATION_BLOCKER);
for (const [name, status] of Object.entries(rows))
  console.log(`${name}: ${status}`);
console.log(`OVERALL: NO_GO (${INTEGRATION_BLOCKER})`);
